apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: identity-service
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - image: nimbleplatform/identity-service
        imagePullPolicy: Always
        name: identity-service
        ports:
        - containerPort: 9096
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
      - image: postgres
        imagePullPolicy: Always
        name: postgres
        ports:
        - containerPort: 5433
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: user